config/routes.rb
Rails.application.routes.draw do
  root "things#index"
  resources :things, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  FOLLOWER_COLOR = ENV["DATABASE_FOLLOWER_COLOR"].to_s.upcase
  FOLLOWER_URL = ENV["HEROKU_POSTGRESQL_#{FOLLOWER_COLOR}_URL"]

  if FOLLOWER_URL.present?
    connects_to database: {writing: :primary, reading: :follower}
  end

  def self.read_only
    if FOLLOWER_URL.present?
      ActiveRecord::Base.connected_to(role: :reading) do
        # All code in this block will run against the follower database.
        # If a write is attempted, an ActiveRecord::ReadOnlyError will raise.
        yield
      end
    else
      # All code in this block will run against the only configured database.
      # Database roles `primary` and `follower` are not available.
      yield
    end
  end
end

app/models/thing.rb
class Thing < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  def index
    ApplicationRecord.read_only do
      @things = Thing.order(created_at: :desc)
    end
  end

  def new
    @thing = Thing.new
  end

  def create
    @thing = Thing.new(params.require(:thing).permit(:name))

    if @thing.save
      redirect_to "/"
    else
      render :new
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>multi-db</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <style>
      :root {
        --content-max-width: 750px;

        --charcoal: rgb(20, 20, 20);
        --purple: rgb(150, 100, 200);
        --purple-faded: rgb(150, 100, 200, .1);
        --tan: rgb(255, 240, 230);

        --body-bg: var(--tan);
        --body-fg: var(--charcoal);
      }

      @media (prefers-color-scheme: dark) {
        :root {
          --body-bg: rgb(25, 30, 45);
          --body-fg: rgb(255, 255, 255);
        }
      }
      html, body {
        font-family: system-ui, -apple-system, Roboto, "Helvetica", "Arial", sans-serif;
        margin: 0;
        padding: 0;
      }
      @supports (font-variation-settings: normal) {
        html, body {
          font-family: system-ui, -apple-system, Roboto, "Helvetica", "Arial", sans-serif;
        }
      }
      body {
        background-color: var(--body-bg);
        color: var(--body-fg);
        font-size: 24px;
        line-height: 36px;
        text-rendering: optimizelegibility;
        -webkit-font-smoothing: antialiased;
      }
      a {
        border-bottom: 1px solid var(--purple);
        color: var(--body-fg);
        text-decoration: none;
        transition: all .1s;
      }
      a:hover {
        border-bottom: 2px solid var(--purple);
        color: var(--purple);
      }
      .container {
        margin: 3rem;
        max-width: var(--content-max-width);
      }
      @media (max-width: 1000px) {
        .container {
          margin: 2rem;
        }
      }
      @media (max-width: 600px) {
        body {
          font-size: 18px;
          line-height: 30px;
        }
        .container {
          margin: 1rem;
          max-width: 92.5%;
          width: 1000px;
        }
      }
      ul {
        list-style-type: none;
        padding-inline-start: 0;
      }
      li {
        margin: 10px 0;
      }
    </style>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/things/index.html.erb
<h1>Things</h1>

<%= link_to 'New thing', new_thing_path %>

<ul>
  <% @things.each do |thing| %>
    <li><%= thing.name %></li>
  <% end %>
</ul>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= form_with(model: @thing) do |form| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @thing.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit "Create" %>
  </div>
<% end %>